name: AWS Terraform Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  lacework-scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan the repo for vulnerabilities in IaC
        run: |
             # Required to pass the GITHUB and Lacework (LW) environment variables to use
             env | grep "GITHUB_\|LW_\|CI_" > env.list
             # Required command based on what you want to scan in the repository
             echo "SCAN_COMMAND=tf-scan" >> env.list
             # Required if you are not mounting the volume on /app
             echo "WORKSPACE=src" >> env.list
             # if we want to fail the step for any critical failed findings (violations) in the assessment scan
             #echo "EXIT_FLAG='critical'" >> env.list 
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
          #LW_SCANNER_SAVE_RESULTS: ${{ secrets.LW_SCANNER_SAVE_RESULTS }}


  # CD Deploy Stage ##
  cd-deploy:
    runs-on: ubuntu-latest
    needs: lacework-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init \
            -backend-config="storage_account_name=tspontes7xg2dfzesta001" \
            -backend-config="container_name=terraform" \
            -backend-config="key=aws.tfstate" \
            -backend-config="sas_token=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2024-06-26T20:08:08Z&st=2024-06-26T12:08:08Z&spr=https,http&sig=DRxJpnzKAKp7snOS2rg5xdEa%2B3ieID1QqHzhXaDvbdU%3D"

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve


        
